### ISSUE TITLE
Mapa mental

### ISSUE THREAD

**Issue by christopheremv** [SistemasTecTlaxiaco/mapa-mental-web-3-christopheremv#1]
[Web 3.0.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-web-3-christopheremv/files/8431094/Web.3.0.pdf)

**Comment by IsaHuerta23** [comment]
Manejo conceptual y dominio del tema: 25 puntos.
Relación entre los conceptos incluidos en el mapa: 22 puntos.
Calidad de la presentación: 22 puntos. 
Jerarquía: 25 puntos: 
TOTAL DE PUNTOS: 94 puntos. 
CALIFICACIÓN: 18/20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
